##????? ?? ????? ???? YML ? ???? ??? ??.
##application.properties ? yml ??? ??? ??? ??.
## ?? ???? HikariCp? ?? ???? database connection? ???.
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/jpatest?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111

  ## ddl-auto? create? ?? ?? app ????? ??? ?? ?? ???? ???
  ## ???? ???? ?? ????? ??.
  jpa:
    properties:
      show_sql: true
      format_sql: true
      hibernate:
        hbm2ddl:
          auto: update

#hibernate? ???? sql ? SYSTEM.OUT ? ???? ?? ??? ???? ?? ??
#logging:
#  level:
#    org.hibernate.SQL:  debug
#    org.hibernate.type: trace
#???? ?? ??? ???? ??? ?? ????? ??? enable-logging ? false? ?? ???? ??? ?????? ??.
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
